insert into township (divistion_id, name) values (2, 'Gyobingauk');
insert into township (divistion_id, name) values (2, 'Letpadan');
insert into township (divistion_id, name) values (2, 'Minhla');
insert into township (divistion_id, name) values (2, 'Monyo');
insert into township (divistion_id, name) values (2, 'Nattalin');
insert into township (divistion_id, name) values (2, 'Okpho');
insert into township (divistion_id, name) values (2, 'Padaung');
insert into township (divistion_id, name) values (2, 'Pauk Kaung');
insert into township (divistion_id, name) values (2, 'Paungde');
insert into township (divistion_id, name) values (2, 'Pyay');
insert into township (divistion_id, name) values (2, 'Shwedaung');
insert into township (divistion_id, name) values (2, 'Thayarwady');
insert into township (divistion_id, name) values (2, 'Thegon');
insert into township (divistion_id, name) values (2, 'Zigo');