insert into township (division_id, name) values (3, 'Falam');
insert into township (division_id, name) values (3, 'Hakha');
insert into township (division_id, name) values (3, 'Htantlang');
insert into township (division_id, name) values (3, 'Kanpetlet');
insert into township (division_id, name) values (3, 'Madupi');
insert into township (division_id, name) values (3, 'Mindat');
insert into township (division_id, name) values (3, 'Paletwa');
insert into township (division_id, name) values (3, 'Tiddim');
insert into township (division_id, name) values (3, 'Tonzang');
