insert into township (division_id, name) values (4, 'Taunggyi');
insert into township (division_id, name) values (4, 'Loilen');
insert into township (division_id, name) values (4, 'Kyaukme');
insert into township (division_id, name) values (4, 'Muse');
insert into township (division_id, name) values (4, 'Laukkaing');
insert into township (division_id, name) values (4, 'Kunlong');
insert into township (division_id, name) values (4, 'Lashio');
insert into township (division_id, name) values (4, 'Keng Tung');
insert into township (division_id, name) values (4, 'mong Hsat');
insert into township (division_id, name) values (4, 'Mong Hpayak');
insert into township (division_id, name) values (4, 'Tachileik');
insert into township (division_id, name) values (4, 'Kalaw');
insert into township (division_id, name) values (4, 'Lawlsawk');
insert into township (division_id, name) values (4, 'Nyaungshwe');
insert into township (division_id, name) values (4, 'Pekon');
insert into township (division_id, name) values (4, 'Pindaya');
insert into township (division_id, name) values (4, 'Ywangon');
insert into township (division_id, name) values (4, 'Hopong');
insert into township (division_id, name) values (4, 'Hi Hseng');
insert into township (division_id, name) values (4, 'Pinlaung');
insert into township (division_id, name) values (4, 'Nansang');
insert into township (division_id, name) values (4, 'Kunhing');
insert into township (division_id, name) values (4, 'Kyethi');
insert into township (division_id, name) values (4, 'Mong Kung');
insert into township (division_id, name) values (4, 'Mong Pan');
insert into township (division_id, name) values (4, 'Mong Hsu');
insert into township (division_id, name) values (4, 'Lai-Hka');
insert into township (division_id, name) values (4, 'Hsipaw');
insert into township (division_id, name) values (4, 'Namtu');
insert into township (division_id, name) values (4, 'Nawnghkio');
insert into township (division_id, name) values (4, 'Mabein');
insert into township (division_id, name) values (4, 'Mongmit');
insert into township (division_id, name) values (4, 'Mu Se');
insert into township (division_id, name) values (4, 'Nankhan');
insert into township (division_id, name) values (4, 'Kongyan');
insert into township (division_id, name) values (4, 'Pangsang');
insert into township (division_id, name) values (4, 'Pangwaun');
insert into township (division_id, name) values (4, 'Mong Khet');
insert into township (division_id, name) values (4, 'Mong Yang');
insert into township (division_id, name) values (4, 'Mong La');
insert into township (division_id, name) values (4, 'Mat Man');
insert into township (division_id, name) values (4, 'Mong Tong');
insert into township (division_id, name) values (4, 'Mong Hsat');
insert into township (division_id, name) values (4, 'Mong Hpayak');
insert into township (division_id, name) values (4, 'Mong Yawng');
