
insert into township (division_id,name) values (14,'Ahlon Township');
insert into township (division_id,name) values (14,'Bahan Township');
insert into township (division_id,name) values (14,'Dagon Township');
insert into township (division_id,name) values (14,'KyauktadaTownship');
insert into township (division_id,name) values (14,'Kyimyindaing Township');
insert into township (division_id,name) values (14,'Lanmadaw Township');
insert into township (division_id,name) values (14,'Latha Township');
insert into township (division_id,name) values (14,'Pabedan Township');
insert into township (division_id,name) values (14,'Sanchaung Township');
insert into township (division_id,name) values (14,'Seikkan Township');
insert into township (division_id,name) values (14,'Botataung Township');
insert into township (division_id,name) values (14,'Dagon Seikkan Township');
insert into township (division_id,name) values (14,'East Dagon Township');
insert into township (division_id,name) values (14,'North Dagon Township');
insert into township (division_id,name) values (14,'North Okkalapa Township');
insert into township (division_id,name) values (14,'Pazundaung Township');
insert into township (division_id,name) values (14,'South Dagon Township');
insert into township (division_id,name) values (14,'South Okkalapa Township');
insert into township (division_id,name) values (14,'Thingangyun Township');
insert into township (division_id,name) values (14,'Mingala Taungnyunt Township');
insert into township (division_id,name) values (14,'Dala Township');
insert into township (division_id,name) values (14,'Dawbon Township');
insert into township (division_id,name) values (14,'Seikkyi Kanaungto Township');
insert into township (division_id,name) values (14,'Tamwe Township');
insert into township (division_id,name) values (14,'Thaketa Township');
insert into township (division_id,name) values (14,'Yankin Township');
insert into township (division_id,name) values (14,'Insein Township');
insert into township (division_id,name) values (14,'Hlaing Township');
insert into township (division_id,name) values (14,'Hlaingthaya Township');
insert into township (division_id,name) values (14,'Kamayut Township');
insert into township (division_id,name) values (14,'Mayangon Township');
insert into township (division_id,name) values (14,'Mingaladon Township');
insert into township (division_id,name) values (14,'Shwepyitha Township');