insert into Division(name) values ('Ayeyarwady Region');
insert into Division(name) values ('Bago Region');
insert into Division(name) values ('Chin State');
insert into Division(name) values ('Kachin State');
insert into Division(name) values ('Kayah State');
insert into Division(name) values ('Kayin State');
insert into Division(name) values ('Magway Region');
insert into Division(name) values ('Mandalay Region');
insert into Division(name) values ('Mon State');
insert into Division(name) values ('Rakhine State');
insert into Division(name) values ('Shan State');
insert into Division(name) values ('Sagaing Region');
insert into Division(name) values ('Tanintharyi Region');
insert into Division(name) values ('Yangon Region');
insert into Division(name) values ('Naypyidaw Union Territory');
insert into township (division_id, name) values (1, 'Hinthada');
insert into township (division_id, name) values (1, 'Lemyethna');
insert into township (division_id, name) values (1, 'Zalun');
insert into township (division_id, name) values (1, 'Ithapyu');
insert into township (division_id, name) values (1, 'Labutta');
insert into township (division_id, name) values (1, 'Mawlamyinegyun');
insert into township (division_id, name) values (1, 'Kyonmanage');
insert into township (division_id, name) values (1, 'Pyinsalu');
insert into township (division_id, name) values (1, 'Danubyu');
insert into township (division_id, name) values (1, 'Ma-ubin');
insert into township (division_id, name) values (1, 'Nyaungdon');
insert into township (division_id, name) values (1, 'Pantanaw');
insert into township (division_id, name) values (1, 'Einme');
insert into township (division_id, name) values (1, 'Myaungmya');
insert into township (division_id, name) values (1, 'Wakema');
insert into township (division_id, name) values (1, 'Shwelaung');
insert into township (division_id, name) values (1, 'Kangyidaunk');
insert into township (division_id, name) values (1, 'Ngapudaw');
insert into township (division_id, name) values (1, 'Pathein');
insert into township (division_id, name) values (1, 'Thabaung');
insert into township (division_id, name) values (1, 'Chaungtha');
insert into township (division_id, name) values (1, 'Hainggyi');
insert into township (division_id, name) values (1, 'Ngayokekaung');
insert into township (division_id, name) values (1, 'Ngwesaung');
insert into township (division_id, name) values (1, 'Bogale');
insert into township (division_id, name) values (1, 'Dedaye');
insert into township (division_id, name) values (1, 'Kyaiklat');
insert into township (division_id, name) values (1, 'Pyapon');
insert into township (division_id, name) values (1, 'Ahmar');
insert into township (division_id, name) values (1, 'Kyaunggon');
insert into township (division_id, name) values (1, 'Kyonpyaw');
insert into township (division_id, name) values (1, 'Yekyi');
insert into township (division_id, name) values (1, 'Ahtaung');
insert into township (division_id, name) values (1, 'Ngathinechaung');
insert into township (division_id, name) values (1, 'Ingapu');
insert into township (division_id, name) values (1, 'Kyangin');
insert into township (division_id, name) values (1, 'Myanaung');
insert into township (division_id, name) values (1, 'Kanaung');

insert into township (division_id, name) values (2, 'Bago');
insert into township (division_id, name) values (2, 'Daik-U');
insert into township (division_id, name) values (2, 'Kawa');
insert into township (division_id, name) values (2, 'Kyaukkyi');
insert into township (division_id, name) values (2, 'Kyauktaga');
insert into township (division_id, name) values (2, 'Nyaunglebin');
insert into township (division_id, name) values (2, 'Oktwin');
insert into township (division_id, name) values (2, 'Phyu');
insert into township (division_id, name) values (2, 'Shwegyin');
insert into township (division_id, name) values (2, 'Tantabi');
insert into township (division_id, name) values (2, 'Taungoo');
insert into township (division_id, name) values (2, 'Thanatpin');
insert into township (division_id, name) values (2, 'Waw');
insert into township (division_id, name) values (2, 'Yedashe');
insert into township (division_id, name) values (2, 'Gyobingauk');
insert into township (division_id, name) values (2, 'Letpadan');
insert into township (division_id, name) values (2, 'Minhla');
insert into township (division_id, name) values (2, 'Monyo');
insert into township (division_id, name) values (2, 'Nattalin');
insert into township (division_id, name) values (2, 'Okpho');
insert into township (division_id, name) values (2, 'Padaung');
insert into township (division_id, name) values (2, 'Pauk Kaung');
insert into township (division_id, name) values (2, 'Paungde');
insert into township (division_id, name) values (2, 'Pyay');
insert into township (division_id, name) values (2, 'Shwedaung');
insert into township (division_id, name) values (2, 'Thayarwady');
insert into township (division_id, name) values (2, 'Thegon');
insert into township (division_id, name) values (2, 'Zigo');

insert into township (division_id, name) values (3, 'Falam ');
insert into township (division_id, name) values (3, 'Hakha');
insert into township (division_id, name) values (3, 'Htantlang');
insert into township (division_id, name) values (3, 'Kanpetlet');
insert into township (division_id, name) values (3, 'Madupi');
insert into township (division_id, name) values (3, 'Mindat');
insert into township (division_id, name) values (3, 'Paletwa');
insert into township (division_id, name) values (3, 'Tiddim');
insert into township (division_id, name) values (3, 'Tonzang');

insert into township (division_id, name) values (4,'Bhamo');
insert into township (division_id, name) values (4,'Chipwi');
insert into township (division_id, name) values (4,'Hsawlaw');
insert into township (division_id, name) values (4,'Hsinbo');
insert into township (division_id, name) values (4,'Hopin');
insert into township (division_id, name) values (4,'Injangyang');
insert into township (division_id, name) values (4,'Kamaing');
insert into township (division_id, name) values (4,'Kawnglanghpu');
insert into township (division_id, name) values (4,'Lweje');
insert into township (division_id, name) values (4,'Machanbaw');
insert into township (division_id, name) values (4,'Mansi');
insert into township (division_id, name) values (4,'Mogaung');
insert into township (division_id, name) values (4,'Mohnyin');
insert into township (division_id, name) values (4,'Momauk');
insert into township (division_id, name) values (4,'Myitkyina');
insert into township (division_id, name) values (4,'Phakant');
insert into township (division_id, name) values (4,'Putao');
insert into township (division_id, name) values (4,'Shwegu');
insert into township (division_id, name) values (4,'Sumprabum');
insert into township (division_id, name) values (4,'Tanai');
insert into township (division_id, name) values (4,'Nogmung');
insert into township (division_id, name) values (4,'Waingmaw');
insert into township (division_id, name) values (4,'Ywathit');

insert into township (division_id, name) values (5, 'Bawlakhe');
insert into township (division_id, name) values (5, 'Demoso');
insert into township (division_id, name) values (5, 'Hpasawng');
insert into township (division_id, name) values (5, 'Hpruso');
insert into township (division_id, name) values (5, 'Kyephogy');
insert into township (division_id, name) values (5, 'Loikaw Township');
insert into township (division_id, name) values (5, 'Mese');
insert into township (division_id, name) values (5, 'Shadaw');

insert into township (division_id, name) values(6, 'Hpa-an');
insert into township (division_id, name) values(6, 'Hlaingbwe');
insert into township (division_id, name) values(6, 'Hpapun');
insert into township (division_id, name) values(6, 'Thandaunggyi');
insert into township (division_id, name) values(6, 'Myawaddy');
insert into township (division_id, name) values(6, 'Kawkareik');
insert into township (division_id, name) values(6, 'Kyainseikgyi');
insert into township (division_id, name) values(6, 'Paing Kyone');

insert into township (division_id, name) values(7,'Magway');
insert into township (division_id, name) values(7,'Myothit');
insert into township (division_id, name) values(7,'Natmauk');
insert into township (division_id, name) values(7,'Yenangyaung');
insert into township (division_id, name) values(7,'Minbu');
insert into township (division_id, name) values(7,'Ngape' );
insert into township (division_id, name) values(7,'Pwintbyu');
insert into township (division_id, name) values(7,'Salin');
insert into township (division_id, name) values(7,'Sidoktaya');	
insert into township (division_id, name) values(7,'Myaing');
insert into township (division_id, name) values(7,'Pakokku');
insert into township (division_id, name) values(7,'Pauk');
insert into township (division_id, name) values(7,'Seikphyu');
insert into township (division_id, name) values(7,'Yesagyo');
insert into township (division_id, name) values(7,'Aunglan'); 
insert into township (division_id, name) values(7,'Kamma');
insert into township (division_id, name) values(7,'Mindon');
insert into township (division_id, name) values(7,'Minhla');
insert into township (division_id, name) values(7,'Sinbaungwe');
insert into township (division_id, name) values(7,'Thayet');
insert into township (division_id, name) values(7,'Gangaw');
insert into township (division_id, name) values(7,'Saw');
insert into township (division_id, name) values(7,'Tilin');
insert into township (division_id, name) values(7,'Kyaukhtu Su');

insert into township (division_id,name) values (8,'Amarapura');
insert into township (division_id,name) values (8,'Aungmyethazan');
insert into township (division_id,name) values (8,'Chanayethazan');
insert into township (division_id,name) values (8,'Chanmyathazi');
insert into township (division_id,name) values (8,'Maha Aungmye');
insert into township (division_id,name) values (8,'Patheingyi');
insert into township (division_id,name) values (8,'Pyigyidagun');

insert into township (division_id,name) values (9,'Mawlamyine');
insert into township (division_id,name) values (9,'Thaton');
insert into township (division_id,name) values (9,'Thanbyuzayat');
insert into township (division_id,name) values (9,'Ye');
insert into township (division_id,name) values (9,'Kyaikmaraw');
insert into township (division_id,name) values (9,'Kyaikhto');
insert into township (division_id,name) values (9,'Bakwai');
insert into township (division_id,name) values (9,'Chaungzon');

insert into township (division_id, name) values (10, 'Sittwe');
insert into township (division_id, name) values (10, 'Mrauk_U');
insert into township (division_id, name) values (10, 'Maungdaw');
insert into township (division_id, name) values (10, 'Kyaukphyu');
insert into township (division_id, name) values (10, 'Thandwe');
insert into township (division_id, name) values (10, 'Pauktaw');
insert into township (division_id, name) values (10, 'Ponnagyun');
insert into township (division_id, name) values (10, 'Rathedaung');
insert into township (division_id, name) values (10, 'Kyauttaw');
insert into township (division_id, name) values (10, 'Myebon');
insert into township (division_id, name) values (10, 'Minbya');
insert into township (division_id, name) values (10, 'Buthidaun');
insert into township (division_id, name) values (10, 'Gwa');
insert into township (division_id, name) values (10, 'Maei-Sub');
insert into township (division_id, name) values (10, 'Kyeintali');
insert into township (division_id, name) values (10, 'Toungup');

insert into township (division_id, name) values (11, 'Taunggyi');
insert into township (division_id, name) values (11, 'Loilen');
insert into township (division_id, name) values (11, 'Kyaukme');
insert into township (division_id, name) values (11, 'Muse');
insert into township (division_id, name) values (11, 'Laukkaing');
insert into township (division_id, name) values (11, 'Kunlong');
insert into township (division_id, name) values (11, 'Lashio');
insert into township (division_id, name) values (11, 'Keng Tung');
insert into township (division_id, name) values (11, 'mong Hsat');
insert into township (division_id, name) values (11, 'Mong Hpayak');
insert into township (division_id, name) values (11, 'Tachileik');
insert into township (division_id, name) values (11, 'Kalaw');
insert into township (division_id, name) values (11, 'Lawlsawk');
insert into township (division_id, name) values (11, 'Nyaungshwe');
insert into township (division_id, name) values (11, 'Pekon');
insert into township (division_id, name) values (11, 'Pindaya');
insert into township (division_id, name) values (11, 'Ywangon');
insert into township (division_id, name) values (11, 'Hopong');
insert into township (division_id, name) values (11, 'Hi Hseng');
insert into township (division_id, name) values (11, 'Pinlaung');
insert into township (division_id, name) values (11, 'Nansang');
insert into township (division_id, name) values (11, 'Kunhing');
insert into township (division_id, name) values (11, 'Kyethi');
insert into township (division_id, name) values (11, 'Mong Kung');
insert into township (division_id, name) values (11, 'Mong Pan');
insert into township (division_id, name) values (11, 'Mong Hsu');
insert into township (division_id, name) values (11, 'Lai-Hka');
insert into township (division_id, name) values (11, 'Hsipaw');
insert into township (division_id, name) values (11, 'Namtu');
insert into township (division_id, name) values (11, 'Nawnghkio');
insert into township (division_id, name) values (11, 'Mabein');
insert into township (division_id, name) values (11, 'Mongmit');
insert into township (division_id, name) values (11, 'Mu Se');
insert into township (division_id, name) values (11, 'Nankhan Township');
insert into township (division_id, name) values (11, 'Kongyan');
insert into township (division_id, name) values (11, 'Pangsang');
insert into township (division_id, name) values (11, 'Pangwaun');
insert into township (division_id, name) values (11, 'Mong Khet');
insert into township (division_id, name) values (11, 'Mong Yang');
insert into township (division_id, name) values (11, 'Mong La');
insert into township (division_id, name) values (11, 'Mat Man');
insert into township (division_id, name) values (11, 'Mong Tong');
insert into township (division_id, name) values (11, 'Mong Hsat');
insert into township (division_id, name) values (11, 'Mong Hpayak');
insert into township (division_id, name) values (11, 'Mong Yawng');

insert into township (division_id, name) values (12, 'Ayadaw');
insert into township (division_id, name) values (12, 'Banmauk');
insert into township (division_id, name) values (12, 'Budalin');
insert into township (division_id, name) values (12, 'Chaung-U');
insert into township (division_id, name) values (12, 'Hkamti');
insert into township (division_id, name) values (12, 'Homalin');
insert into township (division_id, name) values (12, 'Indaw');
insert into township (division_id, name) values (12, 'Kale');
insert into township (division_id, name) values (12, 'Kalewa');
insert into township (division_id, name) values (12, 'Kanbalu');
insert into township (division_id, name) values (12, 'Kani');
insert into township (division_id, name) values (12, 'Katha');
insert into township (division_id, name) values (12, 'Kawlin');
insert into township (division_id, name) values (12, 'Khin-U');
insert into township (division_id, name) values (12, 'Kyunhla');
insert into township (division_id, name) values (12, 'Mawlaik');
insert into township (division_id, name) values (12, 'Mingin Township');
insert into township (division_id, name) values (12, 'Monywa');
insert into township (division_id, name) values (12, 'Myaung');
insert into township (division_id, name) values (12, 'Myinmu');
insert into township (division_id, name) values (12, 'Pale');
insert into township (division_id, name) values (12, 'Paungbyin');
insert into township (division_id, name) values (12, 'Pinlebu');
insert into township (division_id, name) values (12, 'Sagaing');
insert into township (division_id, name) values (12, 'Salingyi');
insert into township (division_id, name) values (12, 'Shwebo');
insert into township (division_id, name) values (12, 'Depeyin');
insert into township (division_id, name) values (12, 'Tamu');
insert into township (division_id, name) values (12, 'Taze');
insert into township (division_id, name) values (12, 'Tigyaing');
insert into township (division_id, name) values (12, 'Wetlet');
insert into township (division_id, name) values (12, 'Wuntho');
insert into township (division_id, name) values (12, 'Ye-U');
insert into township (division_id, name) values (12, 'Yinmabin');

insert into township (division_id, name) values (13, 'Dawei');
insert into township (division_id, name) values (13, 'Launglon');
insert into township (division_id, name) values (13, 'Thayetchaung');
insert into township (division_id, name) values (13, 'Yebyu');
insert into township (division_id, name) values (13, 'Tanjung Kawthaung');
insert into township (division_id, name) values (13, 'Bokfin');
insert into township (division_id, name) values (13, 'Myeik');
insert into township (division_id, name) values (13, 'Kyunsu');
insert into township (division_id, name) values (13, 'Palaw');
insert into township (division_id, name) values (13, 'Taninthayi');

insert into township (division_id,name) values (14,'Ahlon');
insert into township (division_id,name) values (14,'Bahan');
insert into township (division_id,name) values (14,'Dagon');
insert into township (division_id,name) values (14,'Kyauktad');
insert into township (division_id,name) values (14,'Kyimyindaing');
insert into township (division_id,name) values (14,'Lanmadaw');
insert into township (division_id,name) values (14,'Latha');
insert into township (division_id,name) values (14,'Pabedan');
insert into township (division_id,name) values (14,'Sanchaung');
insert into township (division_id,name) values (14,'Seikkan');
insert into township (division_id,name) values (14,'Botataung');
insert into township (division_id,name) values (14,'Dagon Seikkan');
insert into township (division_id,name) values (14,'East Dagon');
insert into township (division_id,name) values (14,'North Dagon');
insert into township (division_id,name) values (14,'North Okkalapa');
insert into township (division_id,name) values (14,'Pazundaung');
insert into township (division_id,name) values (14,'South Dagon');
insert into township (division_id,name) values (14,'South Okkalapa');
insert into township (division_id,name) values (14,'Thingangyun');
insert into township (division_id,name) values (14,'Mingala Taungnyunt');
insert into township (division_id,name) values (14,'Dala');
insert into township (division_id,name) values (14,'Dawbon');
insert into township (division_id,name) values (14,'Seikkyi Kanaungto');
insert into township (division_id,name) values (14,'Tamwe');
insert into township (division_id,name) values (14,'Thaketa');
insert into township (division_id,name) values (14,'Yankin');
insert into township (division_id,name) values (14,'Insein');
insert into township (division_id,name) values (14,'Hlaing');
insert into township (division_id,name) values (14,'Hlaingthaya');
insert into township (division_id,name) values (14,'Kamayut');
insert into township (division_id,name) values (14,'Mayangon');
insert into township (division_id,name) values (14,'Mingaladon');
insert into township (division_id,name) values (14,'Shwepyitha');

insert into township (division_id,name) values(15,'Zeyatheiddhi');
insert into township (division_id,name) values(15,'Pyinnyatheddhi');
insert into township (division_id,name) values(15,'Bawgatheiddhi');
insert into township (division_id,name) values(15,'Mingalatheiddhi');
insert into township (division_id,name) values(15,'Pyinmana');
insert into township (division_id,name) values(15,'Lewe');
insert into township (division_id,name) values(15,'Tatkone');
insert into township (division_id,name) values(15,'Ottarathiri');
insert into township (division_id,name) values(15,'Dekkhinathiri');
insert into township (division_id,name) values(15,'Pobbathiri');
insert into township (division_id,name) values(15,'Zabuthiri');
insert into township (division_id,name) values(15,'Zeyarthiri');

insert into Account (phone, name, role, del_flag, password) values ('admin', 'Admin User', 'ROLE_Admin', false, '$2a$10$M2HV.7p3K0LX6hN7I.aqcOXiuMpen1wWJdPYgdrhASZG.XSewSSoG');
insert into Account (phone, name, role, del_flag, password) values ('member', 'Member', 'ROLE_Member', false, '$2a$10$M2HV.7p3K0LX6hN7I.aqcOXiuMpen1wWJdPYgdrhASZG.XSewSSoG');
insert into Account (phone, name, role, del_flag, password) values ('partner', 'Partner', 'ROLE_Partner', false, '$2a$10$M2HV.7p3K0LX6hN7I.aqcOXiuMpen1wWJdPYgdrhASZG.XSewSSoG');

insert into member(phone) values ('member');
	
insert into family_member (id, member_phone, name) values (1, 'member', 'Kyaw Kyaw');
insert into family_member (id, member_phone, name) values (2, 'member', 'Aung Aung');
insert into family_member (id, member_phone, name) values (3, 'member', 'Maung Maung');
	
insert into partner(phone) values ('partner');


