insert into Division(name) values ('Ayeyarwady Region');
insert into Division(name) values ('Bago Region');
insert into Division(name) values ('Chin State');
insert into Division(name) values ('Kachin State');
insert into Division(name) values ('Kayah State');
insert into Division(name) values ('Kayin State');
insert into Division(name) values ('Magway Region');
insert into Division(name) values ('Mandalay Region');
insert into Division(name) values ('Mon State');
insert into Division(name) values ('Rakhine State');
insert into Division(name) values ('Shan State');
insert into Division(name) values ('Sagaing Region');
insert into Division(name) values ('Tanintharyi Region');
insert into Division(name) values ('Yangon Region');
insert into Division(name) values ('Naypyidaw Union Territory');
insert into township (division_id, name) values (1, 'Hinthada Township');
insert into township (division_id, name) values (1, 'Lemyethna Township');
insert into township (division_id, name) values (1, 'Zalun Township');
insert into township (division_id, name) values (1, 'Ithapyu Township');
insert into township (division_id, name) values (1, 'Labutta Township');
insert into township (division_id, name) values (1, 'Mawlamyinegyun Township');
insert into township (division_id, name) values (1, 'Kyonmanage Township');
insert into township (division_id, name) values (1, 'Pyinsalu Township');
insert into township (division_id, name) values (1, 'Danubyu Township');
insert into township (division_id, name) values (1, 'Ma-ubin Township');
insert into township (division_id, name) values (1, 'Nyaungdon Township');
insert into township (division_id, name) values (1, 'Pantanaw Township');
insert into township (division_id, name) values (1, 'Einme Township');
insert into township (division_id, name) values (1, 'Myaungmya Township');
insert into township (division_id, name) values (1, 'Wakema Township');
insert into township (division_id, name) values (1, 'Shwelaung Township');
insert into township (division_id, name) values (1, 'Kangyidaunk Township');
insert into township (division_id, name) values (1, 'Ngapudaw Township');
insert into township (division_id, name) values (1, 'Pathein Township');
insert into township (division_id, name) values (1, 'Thabaung Township');
insert into township (division_id, name) values (1, 'Chaungtha Township');
insert into township (division_id, name) values (1, 'Hainggyi Township');
insert into township (division_id, name) values (1, 'Ngayokekaung Township');
insert into township (division_id, name) values (1, 'Ngwesaung Township');
insert into township (division_id, name) values (1, 'Bogale Township');
insert into township (division_id, name) values (1, 'Dedaye Township');
insert into township (division_id, name) values (1, 'Kyaiklat Township');
insert into township (division_id, name) values (1, 'Pyapon Township');
insert into township (division_id, name) values (1, 'Ahmar Township');
insert into township (division_id, name) values (1, 'Kyaunggon Township');
insert into township (division_id, name) values (1, 'Kyonpyaw Township');
insert into township (division_id, name) values (1, 'Yekyi Township');
insert into township (division_id, name) values (1, 'Ahtaung Township');
insert into township (division_id, name) values (1, 'Ngathinechaung Township');
insert into township (division_id, name) values (1, 'Ingapu Township');
insert into township (division_id, name) values (1, 'Kyangin Township');
insert into township (division_id, name) values (1, 'Myanaung Township');
insert into township (division_id, name) values (1, 'Kanaung Township');
insert into township (division_id, name) values (2, 'Gyobingauk');
insert into township (division_id, name) values (2, 'Letpadan');
insert into township (division_id, name) values (2, 'Minhla');
insert into township (division_id, name) values (2, 'Monyo');
insert into township (division_id, name) values (2, 'Nattalin');
insert into township (division_id, name) values (2, 'Okpho');
insert into township (division_id, name) values (2, 'Padaung');
insert into township (division_id, name) values (2, 'Pauk Kaung');
insert into township (division_id, name) values (2, 'Paungde');
insert into township (division_id, name) values (2, 'Pyay');
insert into township (division_id, name) values (2, 'Shwedaung');
insert into township (division_id, name) values (2, 'Thayarwady');
insert into township (division_id, name) values (2, 'Thegon');
insert into township (division_id, name) values (2, 'Zigo');
insert into township (division_id, name) values (3, 'Falam');
insert into township (division_id, name) values (3, 'Hakha');
insert into township (division_id, name) values (3, 'Htantlang');
insert into township (division_id, name) values (3, 'Kanpetlet');
insert into township (division_id, name) values (3, 'Madupi');
insert into township (division_id, name) values (3, 'Mindat');
insert into township (division_id, name) values (3, 'Paletwa');
insert into township (division_id, name) values (3, 'Tiddim');
insert into township (division_id, name) values (3, 'Tonzang');

